controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
save_score:
    path: /save-score
    controller: App\Controller\QuizzController::saveScore
    methods: [POST]

